on: [push]
  ...
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://codeberg.org/antoniorodr/lexy'
            GIT_USERNAME: antoniorodr
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
